# Generated by Django 4.1.4 on 2022-12-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
