# Generated by Django 4.1.4 on 2022-12-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rename_author_comment_user_rename_author_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
