# Generated by Django 4.1.4 on 2023-01-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_remove_comment_dislike_remove_post_dislike_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
